name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main # Triggers the build whenever you commit changes to main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Frontend Folder to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend # This isolates your frontend directory
          branch: gh-pages # This sends it to the deployment branch
